# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuser',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fuser',
            name='pw',
            field=models.CharField(default='core@xyz', max_length=255),
        ),
        migrations.AddField(
            model_name='fuser',
            name='un',
            field=models.CharField(default='core', max_length=255),
        ),
    ]
