# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20180403_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuser',
            old_name='no',
            new_name='nop',
        ),
    ]
